# Generated by Django 4.1.7 on 2023-02-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
    ]
