# Generated by Django 4.1.7 on 2023-02-25 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0006_quiz_owner_alter_quizmodel_ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
