# Generated by Django 4.1.7 on 2023-02-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0007_quiz_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='quiz',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
