# Generated by Django 4.1.7 on 2023-02-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0008_remove_quiz_shared_with_quiz_shared_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
